/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ActionInitParameters struct {

	// Target that traffic is routed to when a request matches the gateway route.
	Target []TargetInitParameters `json:"target,omitempty" tf:"target,omitempty"`
}

type ActionObservation struct {

	// Target that traffic is routed to when a request matches the gateway route.
	Target []TargetObservation `json:"target,omitempty" tf:"target,omitempty"`
}

type ActionParameters struct {

	// Target that traffic is routed to when a request matches the gateway route.
	Target []TargetParameters `json:"target,omitempty" tf:"target,omitempty"`
}

type ActionRewriteInitParameters struct {

	// Host name to rewrite.
	Hostname []RewriteHostnameInitParameters `json:"hostname,omitempty" tf:"hostname,omitempty"`

	// Specified beginning characters to rewrite.
	Prefix []RewritePrefixInitParameters `json:"prefix,omitempty" tf:"prefix,omitempty"`
}

type ActionRewriteObservation struct {

	// Host name to rewrite.
	Hostname []RewriteHostnameObservation `json:"hostname,omitempty" tf:"hostname,omitempty"`

	// Specified beginning characters to rewrite.
	Prefix []RewritePrefixObservation `json:"prefix,omitempty" tf:"prefix,omitempty"`
}

type ActionRewriteParameters struct {

	// Host name to rewrite.
	Hostname []RewriteHostnameParameters `json:"hostname,omitempty" tf:"hostname,omitempty"`

	// Specified beginning characters to rewrite.
	Prefix []RewritePrefixParameters `json:"prefix,omitempty" tf:"prefix,omitempty"`
}

type ActionTargetInitParameters struct {

	// Virtual service gateway route target.
	VirtualService []TargetVirtualServiceInitParameters `json:"virtualService,omitempty" tf:"virtual_service,omitempty"`
}

type ActionTargetObservation struct {

	// Virtual service gateway route target.
	VirtualService []TargetVirtualServiceObservation `json:"virtualService,omitempty" tf:"virtual_service,omitempty"`
}

type ActionTargetParameters struct {

	// Virtual service gateway route target.
	VirtualService []TargetVirtualServiceParameters `json:"virtualService,omitempty" tf:"virtual_service,omitempty"`
}

type ActionTargetVirtualServiceInitParameters struct {

	// Name of the virtual service that traffic is routed to. Must be between 1 and 255 characters in length.
	// +crossplane:generate:reference:type=github.com/upbound/provider-aws/apis/appmesh/v1beta1.VirtualService
	// +crossplane:generate:reference:extractor=github.com/upbound/upjet/pkg/resource.ExtractParamPath("name",false)
	VirtualServiceName *string `json:"virtualServiceName,omitempty" tf:"virtual_service_name,omitempty"`

	VirtualServiceNameRef *v1.Reference `json:"virtualServiceNameRef,omitempty" tf:"-"`

	VirtualServiceNameSelector *v1.Selector `json:"virtualServiceNameSelector,omitempty" tf:"-"`
}

type ActionTargetVirtualServiceObservation struct {

	// Name of the virtual service that traffic is routed to. Must be between 1 and 255 characters in length.
	VirtualServiceName *string `json:"virtualServiceName,omitempty" tf:"virtual_service_name,omitempty"`
}

type ActionTargetVirtualServiceParameters struct {

	// Name of the virtual service that traffic is routed to. Must be between 1 and 255 characters in length.
	// +crossplane:generate:reference:type=github.com/upbound/provider-aws/apis/appmesh/v1beta1.VirtualService
	// +crossplane:generate:reference:extractor=github.com/upbound/upjet/pkg/resource.ExtractParamPath("name",false)
	VirtualServiceName *string `json:"virtualServiceName,omitempty" tf:"virtual_service_name,omitempty"`

	// Reference to a VirtualService in appmesh to populate virtualServiceName.
	// +kubebuilder:validation:Optional
	VirtualServiceNameRef *v1.Reference `json:"virtualServiceNameRef,omitempty" tf:"-"`

	// Selector for a VirtualService in appmesh to populate virtualServiceName.
	// +kubebuilder:validation:Optional
	VirtualServiceNameSelector *v1.Selector `json:"virtualServiceNameSelector,omitempty" tf:"-"`
}

type GRPCRouteInitParameters struct {

	// Action to take if a match is determined.
	Action []ActionInitParameters `json:"action,omitempty" tf:"action,omitempty"`

	// Criteria for determining a request match.
	Match []MatchInitParameters `json:"match,omitempty" tf:"match,omitempty"`
}

type GRPCRouteObservation struct {

	// Action to take if a match is determined.
	Action []ActionObservation `json:"action,omitempty" tf:"action,omitempty"`

	// Criteria for determining a request match.
	Match []MatchObservation `json:"match,omitempty" tf:"match,omitempty"`
}

type GRPCRouteParameters struct {

	// Action to take if a match is determined.
	Action []ActionParameters `json:"action,omitempty" tf:"action,omitempty"`

	// Criteria for determining a request match.
	Match []MatchParameters `json:"match,omitempty" tf:"match,omitempty"`
}

type GatewayRouteInitParameters struct {

	// Name of the service mesh in which to create the gateway route. Must be between 1 and 255 characters in length.
	MeshName *string `json:"meshName,omitempty" tf:"mesh_name,omitempty"`

	// AWS account ID of the service mesh's owner. Defaults to the account ID the AWS provider is currently connected to.
	MeshOwner *string `json:"meshOwner,omitempty" tf:"mesh_owner,omitempty"`

	// Name to use for the gateway route. Must be between 1 and 255 characters in length.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Region is the region you'd like your resource to be created in.
	// +upjet:crd:field:TFTag=-
	Region *string `json:"region,omitempty" tf:"-"`

	// Gateway route specification to apply.
	Spec []SpecInitParameters `json:"spec,omitempty" tf:"spec,omitempty"`

	// Key-value map of resource tags.
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// Name of the virtual gateway to associate the gateway route with. Must be between 1 and 255 characters in length.
	// +crossplane:generate:reference:type=github.com/upbound/provider-aws/apis/appmesh/v1beta1.VirtualGateway
	// +crossplane:generate:reference:extractor=github.com/upbound/upjet/pkg/resource.ExtractParamPath("name",false)
	VirtualGatewayName *string `json:"virtualGatewayName,omitempty" tf:"virtual_gateway_name,omitempty"`

	VirtualGatewayNameRef *v1.Reference `json:"virtualGatewayNameRef,omitempty" tf:"-"`

	VirtualGatewayNameSelector *v1.Selector `json:"virtualGatewayNameSelector,omitempty" tf:"-"`
}

type GatewayRouteObservation struct {

	// ARN of the gateway route.
	Arn *string `json:"arn,omitempty" tf:"arn,omitempty"`

	// Creation date of the gateway route.
	CreatedDate *string `json:"createdDate,omitempty" tf:"created_date,omitempty"`

	// ID of the gateway route.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Last update date of the gateway route.
	LastUpdatedDate *string `json:"lastUpdatedDate,omitempty" tf:"last_updated_date,omitempty"`

	// Name of the service mesh in which to create the gateway route. Must be between 1 and 255 characters in length.
	MeshName *string `json:"meshName,omitempty" tf:"mesh_name,omitempty"`

	// AWS account ID of the service mesh's owner. Defaults to the account ID the AWS provider is currently connected to.
	MeshOwner *string `json:"meshOwner,omitempty" tf:"mesh_owner,omitempty"`

	// Name to use for the gateway route. Must be between 1 and 255 characters in length.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Resource owner's AWS account ID.
	ResourceOwner *string `json:"resourceOwner,omitempty" tf:"resource_owner,omitempty"`

	// Gateway route specification to apply.
	Spec []SpecObservation `json:"spec,omitempty" tf:"spec,omitempty"`

	// Key-value map of resource tags.
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// Map of tags assigned to the resource, including those inherited from the provider default_tags configuration block.
	TagsAll map[string]*string `json:"tagsAll,omitempty" tf:"tags_all,omitempty"`

	// Name of the virtual gateway to associate the gateway route with. Must be between 1 and 255 characters in length.
	VirtualGatewayName *string `json:"virtualGatewayName,omitempty" tf:"virtual_gateway_name,omitempty"`
}

type GatewayRouteParameters struct {

	// Name of the service mesh in which to create the gateway route. Must be between 1 and 255 characters in length.
	MeshName *string `json:"meshName,omitempty" tf:"mesh_name,omitempty"`

	// AWS account ID of the service mesh's owner. Defaults to the account ID the AWS provider is currently connected to.
	MeshOwner *string `json:"meshOwner,omitempty" tf:"mesh_owner,omitempty"`

	// Name to use for the gateway route. Must be between 1 and 255 characters in length.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Region is the region you'd like your resource to be created in.
	// +upjet:crd:field:TFTag=-
	Region *string `json:"region,omitempty" tf:"-"`

	// Gateway route specification to apply.
	Spec []SpecParameters `json:"spec,omitempty" tf:"spec,omitempty"`

	// Key-value map of resource tags.
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// Name of the virtual gateway to associate the gateway route with. Must be between 1 and 255 characters in length.
	// +crossplane:generate:reference:type=github.com/upbound/provider-aws/apis/appmesh/v1beta1.VirtualGateway
	// +crossplane:generate:reference:extractor=github.com/upbound/upjet/pkg/resource.ExtractParamPath("name",false)
	VirtualGatewayName *string `json:"virtualGatewayName,omitempty" tf:"virtual_gateway_name,omitempty"`

	// Reference to a VirtualGateway in appmesh to populate virtualGatewayName.
	// +kubebuilder:validation:Optional
	VirtualGatewayNameRef *v1.Reference `json:"virtualGatewayNameRef,omitempty" tf:"-"`

	// Selector for a VirtualGateway in appmesh to populate virtualGatewayName.
	// +kubebuilder:validation:Optional
	VirtualGatewayNameSelector *v1.Selector `json:"virtualGatewayNameSelector,omitempty" tf:"-"`
}

type HTTPRouteActionInitParameters struct {

	// Gateway route action to rewrite.
	Rewrite []ActionRewriteInitParameters `json:"rewrite,omitempty" tf:"rewrite,omitempty"`

	// Target that traffic is routed to when a request matches the gateway route.
	Target []HTTPRouteActionTargetInitParameters `json:"target,omitempty" tf:"target,omitempty"`
}

type HTTPRouteActionObservation struct {

	// Gateway route action to rewrite.
	Rewrite []ActionRewriteObservation `json:"rewrite,omitempty" tf:"rewrite,omitempty"`

	// Target that traffic is routed to when a request matches the gateway route.
	Target []HTTPRouteActionTargetObservation `json:"target,omitempty" tf:"target,omitempty"`
}

type HTTPRouteActionParameters struct {

	// Gateway route action to rewrite.
	Rewrite []ActionRewriteParameters `json:"rewrite,omitempty" tf:"rewrite,omitempty"`

	// Target that traffic is routed to when a request matches the gateway route.
	Target []HTTPRouteActionTargetParameters `json:"target,omitempty" tf:"target,omitempty"`
}

type HTTPRouteActionTargetInitParameters struct {

	// Virtual service gateway route target.
	VirtualService []ActionTargetVirtualServiceInitParameters `json:"virtualService,omitempty" tf:"virtual_service,omitempty"`
}

type HTTPRouteActionTargetObservation struct {

	// Virtual service gateway route target.
	VirtualService []ActionTargetVirtualServiceObservation `json:"virtualService,omitempty" tf:"virtual_service,omitempty"`
}

type HTTPRouteActionTargetParameters struct {

	// Virtual service gateway route target.
	VirtualService []ActionTargetVirtualServiceParameters `json:"virtualService,omitempty" tf:"virtual_service,omitempty"`
}

type HTTPRouteInitParameters struct {

	// Action to take if a match is determined.
	Action []HTTPRouteActionInitParameters `json:"action,omitempty" tf:"action,omitempty"`

	// Criteria for determining a request match.
	Match []HTTPRouteMatchInitParameters `json:"match,omitempty" tf:"match,omitempty"`
}

type HTTPRouteMatchHostnameInitParameters struct {

	// Exact host name to match on.
	Exact *string `json:"exact,omitempty" tf:"exact,omitempty"`

	// Specified ending characters of the host name to match on.
	Suffix *string `json:"suffix,omitempty" tf:"suffix,omitempty"`
}

type HTTPRouteMatchHostnameObservation struct {

	// Exact host name to match on.
	Exact *string `json:"exact,omitempty" tf:"exact,omitempty"`

	// Specified ending characters of the host name to match on.
	Suffix *string `json:"suffix,omitempty" tf:"suffix,omitempty"`
}

type HTTPRouteMatchHostnameParameters struct {

	// Exact host name to match on.
	Exact *string `json:"exact,omitempty" tf:"exact,omitempty"`

	// Specified ending characters of the host name to match on.
	Suffix *string `json:"suffix,omitempty" tf:"suffix,omitempty"`
}

type HTTPRouteMatchInitParameters struct {

	// Host name to rewrite.
	Hostname []HTTPRouteMatchHostnameInitParameters `json:"hostname,omitempty" tf:"hostname,omitempty"`

	// The port number to match from the request.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// Specified beginning characters to rewrite.
	Prefix *string `json:"prefix,omitempty" tf:"prefix,omitempty"`
}

type HTTPRouteMatchObservation struct {

	// Host name to rewrite.
	Hostname []HTTPRouteMatchHostnameObservation `json:"hostname,omitempty" tf:"hostname,omitempty"`

	// The port number to match from the request.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// Specified beginning characters to rewrite.
	Prefix *string `json:"prefix,omitempty" tf:"prefix,omitempty"`
}

type HTTPRouteMatchParameters struct {

	// Host name to rewrite.
	Hostname []HTTPRouteMatchHostnameParameters `json:"hostname,omitempty" tf:"hostname,omitempty"`

	// The port number to match from the request.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// Specified beginning characters to rewrite.
	Prefix *string `json:"prefix,omitempty" tf:"prefix,omitempty"`
}

type HTTPRouteObservation struct {

	// Action to take if a match is determined.
	Action []HTTPRouteActionObservation `json:"action,omitempty" tf:"action,omitempty"`

	// Criteria for determining a request match.
	Match []HTTPRouteMatchObservation `json:"match,omitempty" tf:"match,omitempty"`
}

type HTTPRouteParameters struct {

	// Action to take if a match is determined.
	Action []HTTPRouteActionParameters `json:"action,omitempty" tf:"action,omitempty"`

	// Criteria for determining a request match.
	Match []HTTPRouteMatchParameters `json:"match,omitempty" tf:"match,omitempty"`
}

type HostnameInitParameters struct {

	// Default target host name to write to. Valid values: ENABLED, DISABLED.
	DefaultTargetHostname *string `json:"defaultTargetHostname,omitempty" tf:"default_target_hostname,omitempty"`
}

type HostnameObservation struct {

	// Default target host name to write to. Valid values: ENABLED, DISABLED.
	DefaultTargetHostname *string `json:"defaultTargetHostname,omitempty" tf:"default_target_hostname,omitempty"`
}

type HostnameParameters struct {

	// Default target host name to write to. Valid values: ENABLED, DISABLED.
	DefaultTargetHostname *string `json:"defaultTargetHostname,omitempty" tf:"default_target_hostname,omitempty"`
}

type Http2RouteActionInitParameters struct {

	// Gateway route action to rewrite.
	Rewrite []RewriteInitParameters `json:"rewrite,omitempty" tf:"rewrite,omitempty"`

	// Target that traffic is routed to when a request matches the gateway route.
	Target []ActionTargetInitParameters `json:"target,omitempty" tf:"target,omitempty"`
}

type Http2RouteActionObservation struct {

	// Gateway route action to rewrite.
	Rewrite []RewriteObservation `json:"rewrite,omitempty" tf:"rewrite,omitempty"`

	// Target that traffic is routed to when a request matches the gateway route.
	Target []ActionTargetObservation `json:"target,omitempty" tf:"target,omitempty"`
}

type Http2RouteActionParameters struct {

	// Gateway route action to rewrite.
	Rewrite []RewriteParameters `json:"rewrite,omitempty" tf:"rewrite,omitempty"`

	// Target that traffic is routed to when a request matches the gateway route.
	Target []ActionTargetParameters `json:"target,omitempty" tf:"target,omitempty"`
}

type Http2RouteInitParameters struct {

	// Action to take if a match is determined.
	Action []Http2RouteActionInitParameters `json:"action,omitempty" tf:"action,omitempty"`

	// Criteria for determining a request match.
	Match []Http2RouteMatchInitParameters `json:"match,omitempty" tf:"match,omitempty"`
}

type Http2RouteMatchInitParameters struct {

	// Host name to rewrite.
	Hostname []MatchHostnameInitParameters `json:"hostname,omitempty" tf:"hostname,omitempty"`

	// The port number to match from the request.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// Specified beginning characters to rewrite.
	Prefix *string `json:"prefix,omitempty" tf:"prefix,omitempty"`
}

type Http2RouteMatchObservation struct {

	// Host name to rewrite.
	Hostname []MatchHostnameObservation `json:"hostname,omitempty" tf:"hostname,omitempty"`

	// The port number to match from the request.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// Specified beginning characters to rewrite.
	Prefix *string `json:"prefix,omitempty" tf:"prefix,omitempty"`
}

type Http2RouteMatchParameters struct {

	// Host name to rewrite.
	Hostname []MatchHostnameParameters `json:"hostname,omitempty" tf:"hostname,omitempty"`

	// The port number to match from the request.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// Specified beginning characters to rewrite.
	Prefix *string `json:"prefix,omitempty" tf:"prefix,omitempty"`
}

type Http2RouteObservation struct {

	// Action to take if a match is determined.
	Action []Http2RouteActionObservation `json:"action,omitempty" tf:"action,omitempty"`

	// Criteria for determining a request match.
	Match []Http2RouteMatchObservation `json:"match,omitempty" tf:"match,omitempty"`
}

type Http2RouteParameters struct {

	// Action to take if a match is determined.
	Action []Http2RouteActionParameters `json:"action,omitempty" tf:"action,omitempty"`

	// Criteria for determining a request match.
	Match []Http2RouteMatchParameters `json:"match,omitempty" tf:"match,omitempty"`
}

type MatchHostnameInitParameters struct {

	// Exact host name to match on.
	Exact *string `json:"exact,omitempty" tf:"exact,omitempty"`

	// Specified ending characters of the host name to match on.
	Suffix *string `json:"suffix,omitempty" tf:"suffix,omitempty"`
}

type MatchHostnameObservation struct {

	// Exact host name to match on.
	Exact *string `json:"exact,omitempty" tf:"exact,omitempty"`

	// Specified ending characters of the host name to match on.
	Suffix *string `json:"suffix,omitempty" tf:"suffix,omitempty"`
}

type MatchHostnameParameters struct {

	// Exact host name to match on.
	Exact *string `json:"exact,omitempty" tf:"exact,omitempty"`

	// Specified ending characters of the host name to match on.
	Suffix *string `json:"suffix,omitempty" tf:"suffix,omitempty"`
}

type MatchInitParameters struct {

	// The port number to match from the request.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// Fully qualified domain name for the service to match from the request.
	ServiceName *string `json:"serviceName,omitempty" tf:"service_name,omitempty"`
}

type MatchObservation struct {

	// The port number to match from the request.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// Fully qualified domain name for the service to match from the request.
	ServiceName *string `json:"serviceName,omitempty" tf:"service_name,omitempty"`
}

type MatchParameters struct {

	// The port number to match from the request.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// Fully qualified domain name for the service to match from the request.
	ServiceName *string `json:"serviceName,omitempty" tf:"service_name,omitempty"`
}

type PrefixInitParameters struct {

	// Default prefix used to replace the incoming route prefix when rewritten. Valid values: ENABLED, DISABLED.
	DefaultPrefix *string `json:"defaultPrefix,omitempty" tf:"default_prefix,omitempty"`

	// Value used to replace the incoming route prefix when rewritten.
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type PrefixObservation struct {

	// Default prefix used to replace the incoming route prefix when rewritten. Valid values: ENABLED, DISABLED.
	DefaultPrefix *string `json:"defaultPrefix,omitempty" tf:"default_prefix,omitempty"`

	// Value used to replace the incoming route prefix when rewritten.
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type PrefixParameters struct {

	// Default prefix used to replace the incoming route prefix when rewritten. Valid values: ENABLED, DISABLED.
	DefaultPrefix *string `json:"defaultPrefix,omitempty" tf:"default_prefix,omitempty"`

	// Value used to replace the incoming route prefix when rewritten.
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type RewriteHostnameInitParameters struct {

	// Default target host name to write to. Valid values: ENABLED, DISABLED.
	DefaultTargetHostname *string `json:"defaultTargetHostname,omitempty" tf:"default_target_hostname,omitempty"`
}

type RewriteHostnameObservation struct {

	// Default target host name to write to. Valid values: ENABLED, DISABLED.
	DefaultTargetHostname *string `json:"defaultTargetHostname,omitempty" tf:"default_target_hostname,omitempty"`
}

type RewriteHostnameParameters struct {

	// Default target host name to write to. Valid values: ENABLED, DISABLED.
	DefaultTargetHostname *string `json:"defaultTargetHostname,omitempty" tf:"default_target_hostname,omitempty"`
}

type RewriteInitParameters struct {

	// Host name to rewrite.
	Hostname []HostnameInitParameters `json:"hostname,omitempty" tf:"hostname,omitempty"`

	// Specified beginning characters to rewrite.
	Prefix []PrefixInitParameters `json:"prefix,omitempty" tf:"prefix,omitempty"`
}

type RewriteObservation struct {

	// Host name to rewrite.
	Hostname []HostnameObservation `json:"hostname,omitempty" tf:"hostname,omitempty"`

	// Specified beginning characters to rewrite.
	Prefix []PrefixObservation `json:"prefix,omitempty" tf:"prefix,omitempty"`
}

type RewriteParameters struct {

	// Host name to rewrite.
	Hostname []HostnameParameters `json:"hostname,omitempty" tf:"hostname,omitempty"`

	// Specified beginning characters to rewrite.
	Prefix []PrefixParameters `json:"prefix,omitempty" tf:"prefix,omitempty"`
}

type RewritePrefixInitParameters struct {

	// Default prefix used to replace the incoming route prefix when rewritten. Valid values: ENABLED, DISABLED.
	DefaultPrefix *string `json:"defaultPrefix,omitempty" tf:"default_prefix,omitempty"`

	// Value used to replace the incoming route prefix when rewritten.
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type RewritePrefixObservation struct {

	// Default prefix used to replace the incoming route prefix when rewritten. Valid values: ENABLED, DISABLED.
	DefaultPrefix *string `json:"defaultPrefix,omitempty" tf:"default_prefix,omitempty"`

	// Value used to replace the incoming route prefix when rewritten.
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type RewritePrefixParameters struct {

	// Default prefix used to replace the incoming route prefix when rewritten. Valid values: ENABLED, DISABLED.
	DefaultPrefix *string `json:"defaultPrefix,omitempty" tf:"default_prefix,omitempty"`

	// Value used to replace the incoming route prefix when rewritten.
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type SpecInitParameters struct {

	// Specification of a gRPC gateway route.
	GRPCRoute []GRPCRouteInitParameters `json:"grpcRoute,omitempty" tf:"grpc_route,omitempty"`

	// Specification of an HTTP gateway route.
	HTTPRoute []HTTPRouteInitParameters `json:"httpRoute,omitempty" tf:"http_route,omitempty"`

	// Specification of an HTTP/2 gateway route.
	Http2Route []Http2RouteInitParameters `json:"http2Route,omitempty" tf:"http2_route,omitempty"`
}

type SpecObservation struct {

	// Specification of a gRPC gateway route.
	GRPCRoute []GRPCRouteObservation `json:"grpcRoute,omitempty" tf:"grpc_route,omitempty"`

	// Specification of an HTTP gateway route.
	HTTPRoute []HTTPRouteObservation `json:"httpRoute,omitempty" tf:"http_route,omitempty"`

	// Specification of an HTTP/2 gateway route.
	Http2Route []Http2RouteObservation `json:"http2Route,omitempty" tf:"http2_route,omitempty"`
}

type SpecParameters struct {

	// Specification of a gRPC gateway route.
	GRPCRoute []GRPCRouteParameters `json:"grpcRoute,omitempty" tf:"grpc_route,omitempty"`

	// Specification of an HTTP gateway route.
	HTTPRoute []HTTPRouteParameters `json:"httpRoute,omitempty" tf:"http_route,omitempty"`

	// Specification of an HTTP/2 gateway route.
	Http2Route []Http2RouteParameters `json:"http2Route,omitempty" tf:"http2_route,omitempty"`
}

type TargetInitParameters struct {

	// Virtual service gateway route target.
	VirtualService []VirtualServiceInitParameters `json:"virtualService,omitempty" tf:"virtual_service,omitempty"`
}

type TargetObservation struct {

	// Virtual service gateway route target.
	VirtualService []VirtualServiceObservation `json:"virtualService,omitempty" tf:"virtual_service,omitempty"`
}

type TargetParameters struct {

	// Virtual service gateway route target.
	VirtualService []VirtualServiceParameters `json:"virtualService,omitempty" tf:"virtual_service,omitempty"`
}

type TargetVirtualServiceInitParameters struct {

	// Name of the virtual service that traffic is routed to. Must be between 1 and 255 characters in length.
	VirtualServiceName *string `json:"virtualServiceName,omitempty" tf:"virtual_service_name,omitempty"`
}

type TargetVirtualServiceObservation struct {

	// Name of the virtual service that traffic is routed to. Must be between 1 and 255 characters in length.
	VirtualServiceName *string `json:"virtualServiceName,omitempty" tf:"virtual_service_name,omitempty"`
}

type TargetVirtualServiceParameters struct {

	// Name of the virtual service that traffic is routed to. Must be between 1 and 255 characters in length.
	VirtualServiceName *string `json:"virtualServiceName,omitempty" tf:"virtual_service_name,omitempty"`
}

type VirtualServiceInitParameters struct {

	// Name of the virtual service that traffic is routed to. Must be between 1 and 255 characters in length.
	VirtualServiceName *string `json:"virtualServiceName,omitempty" tf:"virtual_service_name,omitempty"`
}

type VirtualServiceObservation struct {

	// Name of the virtual service that traffic is routed to. Must be between 1 and 255 characters in length.
	VirtualServiceName *string `json:"virtualServiceName,omitempty" tf:"virtual_service_name,omitempty"`
}

type VirtualServiceParameters struct {

	// Name of the virtual service that traffic is routed to. Must be between 1 and 255 characters in length.
	VirtualServiceName *string `json:"virtualServiceName,omitempty" tf:"virtual_service_name,omitempty"`
}

// GatewayRouteSpec defines the desired state of GatewayRoute
type GatewayRouteSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     GatewayRouteParameters `json:"forProvider"`
	// THIS IS AN ALPHA FIELD. Do not use it in production. It is not honored
	// unless the relevant Crossplane feature flag is enabled, and may be
	// changed or removed without notice.
	InitProvider GatewayRouteInitParameters `json:"initProvider,omitempty"`
}

// GatewayRouteStatus defines the observed state of GatewayRoute.
type GatewayRouteStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        GatewayRouteObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// GatewayRoute is the Schema for the GatewayRoutes API. Provides an AWS App Mesh gateway route resource.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,aws}
type GatewayRoute struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.meshName) || has(self.initProvider.meshName)",message="%!s(MISSING) is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || has(self.initProvider.name)",message="%!s(MISSING) is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.spec) || has(self.initProvider.spec)",message="%!s(MISSING) is a required parameter"
	Spec   GatewayRouteSpec   `json:"spec"`
	Status GatewayRouteStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// GatewayRouteList contains a list of GatewayRoutes
type GatewayRouteList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []GatewayRoute `json:"items"`
}

// Repository type metadata.
var (
	GatewayRoute_Kind             = "GatewayRoute"
	GatewayRoute_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: GatewayRoute_Kind}.String()
	GatewayRoute_KindAPIVersion   = GatewayRoute_Kind + "." + CRDGroupVersion.String()
	GatewayRoute_GroupVersionKind = CRDGroupVersion.WithKind(GatewayRoute_Kind)
)

func init() {
	SchemeBuilder.Register(&GatewayRoute{}, &GatewayRouteList{})
}
