/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ActionWeightedTargetInitParameters struct {

	// The port number to match from the request.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// Virtual node to associate with the weighted target. Must be between 1 and 255 characters in length.
	VirtualNode *string `json:"virtualNode,omitempty" tf:"virtual_node,omitempty"`

	// Relative weight of the weighted target. An integer between 0 and 100.
	Weight *float64 `json:"weight,omitempty" tf:"weight,omitempty"`
}

type ActionWeightedTargetObservation struct {

	// The port number to match from the request.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// Virtual node to associate with the weighted target. Must be between 1 and 255 characters in length.
	VirtualNode *string `json:"virtualNode,omitempty" tf:"virtual_node,omitempty"`

	// Relative weight of the weighted target. An integer between 0 and 100.
	Weight *float64 `json:"weight,omitempty" tf:"weight,omitempty"`
}

type ActionWeightedTargetParameters struct {

	// The port number to match from the request.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// Virtual node to associate with the weighted target. Must be between 1 and 255 characters in length.
	VirtualNode *string `json:"virtualNode,omitempty" tf:"virtual_node,omitempty"`

	// Relative weight of the weighted target. An integer between 0 and 100.
	Weight *float64 `json:"weight,omitempty" tf:"weight,omitempty"`
}

type GRPCRouteActionInitParameters struct {

	// Targets that traffic is routed to when a request matches the route.
	// You can specify one or more targets and their relative weights with which to distribute traffic.
	WeightedTarget []WeightedTargetInitParameters `json:"weightedTarget,omitempty" tf:"weighted_target,omitempty"`
}

type GRPCRouteActionObservation struct {

	// Targets that traffic is routed to when a request matches the route.
	// You can specify one or more targets and their relative weights with which to distribute traffic.
	WeightedTarget []WeightedTargetObservation `json:"weightedTarget,omitempty" tf:"weighted_target,omitempty"`
}

type GRPCRouteActionParameters struct {

	// Targets that traffic is routed to when a request matches the route.
	// You can specify one or more targets and their relative weights with which to distribute traffic.
	WeightedTarget []WeightedTargetParameters `json:"weightedTarget,omitempty" tf:"weighted_target,omitempty"`
}

type GRPCRouteMatchInitParameters struct {

	// Data to match from the gRPC request.
	Metadata []MetadataInitParameters `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// Method name to match from the request. If you specify a name, you must also specify a service_name.
	MethodName *string `json:"methodName,omitempty" tf:"method_name,omitempty"`

	// The port number to match from the request.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// Value sent by the client must begin with the specified characters. Must be between 1 and 255 characters in length.
	Prefix *string `json:"prefix,omitempty" tf:"prefix,omitempty"`

	// Fully qualified domain name for the service to match from the request.
	ServiceName *string `json:"serviceName,omitempty" tf:"service_name,omitempty"`
}

type GRPCRouteMatchObservation struct {

	// Data to match from the gRPC request.
	Metadata []MetadataObservation `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// Method name to match from the request. If you specify a name, you must also specify a service_name.
	MethodName *string `json:"methodName,omitempty" tf:"method_name,omitempty"`

	// The port number to match from the request.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// Value sent by the client must begin with the specified characters. Must be between 1 and 255 characters in length.
	Prefix *string `json:"prefix,omitempty" tf:"prefix,omitempty"`

	// Fully qualified domain name for the service to match from the request.
	ServiceName *string `json:"serviceName,omitempty" tf:"service_name,omitempty"`
}

type GRPCRouteMatchParameters struct {

	// Data to match from the gRPC request.
	Metadata []MetadataParameters `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// Method name to match from the request. If you specify a name, you must also specify a service_name.
	MethodName *string `json:"methodName,omitempty" tf:"method_name,omitempty"`

	// The port number to match from the request.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// Value sent by the client must begin with the specified characters. Must be between 1 and 255 characters in length.
	Prefix *string `json:"prefix,omitempty" tf:"prefix,omitempty"`

	// Fully qualified domain name for the service to match from the request.
	ServiceName *string `json:"serviceName,omitempty" tf:"service_name,omitempty"`
}

type HTTPRouteActionWeightedTargetInitParameters struct {

	// The port number to match from the request.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// Virtual node to associate with the weighted target. Must be between 1 and 255 characters in length.
	// +crossplane:generate:reference:type=github.com/upbound/provider-aws/apis/appmesh/v1beta1.VirtualNode
	// +crossplane:generate:reference:extractor=github.com/upbound/upjet/pkg/resource.ExtractParamPath("name",false)
	VirtualNode *string `json:"virtualNode,omitempty" tf:"virtual_node,omitempty"`

	VirtualNodeRef *v1.Reference `json:"virtualNodeRef,omitempty" tf:"-"`

	VirtualNodeSelector *v1.Selector `json:"virtualNodeSelector,omitempty" tf:"-"`

	// Relative weight of the weighted target. An integer between 0 and 100.
	Weight *float64 `json:"weight,omitempty" tf:"weight,omitempty"`
}

type HTTPRouteActionWeightedTargetObservation struct {

	// The port number to match from the request.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// Virtual node to associate with the weighted target. Must be between 1 and 255 characters in length.
	VirtualNode *string `json:"virtualNode,omitempty" tf:"virtual_node,omitempty"`

	// Relative weight of the weighted target. An integer between 0 and 100.
	Weight *float64 `json:"weight,omitempty" tf:"weight,omitempty"`
}

type HTTPRouteActionWeightedTargetParameters struct {

	// The port number to match from the request.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// Virtual node to associate with the weighted target. Must be between 1 and 255 characters in length.
	// +crossplane:generate:reference:type=github.com/upbound/provider-aws/apis/appmesh/v1beta1.VirtualNode
	// +crossplane:generate:reference:extractor=github.com/upbound/upjet/pkg/resource.ExtractParamPath("name",false)
	VirtualNode *string `json:"virtualNode,omitempty" tf:"virtual_node,omitempty"`

	// Reference to a VirtualNode in appmesh to populate virtualNode.
	// +kubebuilder:validation:Optional
	VirtualNodeRef *v1.Reference `json:"virtualNodeRef,omitempty" tf:"-"`

	// Selector for a VirtualNode in appmesh to populate virtualNode.
	// +kubebuilder:validation:Optional
	VirtualNodeSelector *v1.Selector `json:"virtualNodeSelector,omitempty" tf:"-"`

	// Relative weight of the weighted target. An integer between 0 and 100.
	Weight *float64 `json:"weight,omitempty" tf:"weight,omitempty"`
}

type HTTPRouteRetryPolicyInitParameters struct {

	// List of HTTP retry events.
	// Valid values: client-error (HTTP status code 409), gateway-error (HTTP status codes 502, 503, and 504), server-error (HTTP status codes 500, 501, 502, 503, 504, 505, 506, 507, 508, 510, and 511), stream-error (retry on refused stream).
	HTTPRetryEvents []*string `json:"httpRetryEvents,omitempty" tf:"http_retry_events,omitempty"`

	// Maximum number of retries.
	MaxRetries *float64 `json:"maxRetries,omitempty" tf:"max_retries,omitempty"`

	// Per-retry timeout.
	PerRetryTimeout []HTTPRouteRetryPolicyPerRetryTimeoutInitParameters `json:"perRetryTimeout,omitempty" tf:"per_retry_timeout,omitempty"`

	// List of TCP retry events. The only valid value is connection-error.
	TCPRetryEvents []*string `json:"tcpRetryEvents,omitempty" tf:"tcp_retry_events,omitempty"`
}

type HTTPRouteRetryPolicyObservation struct {

	// List of HTTP retry events.
	// Valid values: client-error (HTTP status code 409), gateway-error (HTTP status codes 502, 503, and 504), server-error (HTTP status codes 500, 501, 502, 503, 504, 505, 506, 507, 508, 510, and 511), stream-error (retry on refused stream).
	HTTPRetryEvents []*string `json:"httpRetryEvents,omitempty" tf:"http_retry_events,omitempty"`

	// Maximum number of retries.
	MaxRetries *float64 `json:"maxRetries,omitempty" tf:"max_retries,omitempty"`

	// Per-retry timeout.
	PerRetryTimeout []HTTPRouteRetryPolicyPerRetryTimeoutObservation `json:"perRetryTimeout,omitempty" tf:"per_retry_timeout,omitempty"`

	// List of TCP retry events. The only valid value is connection-error.
	TCPRetryEvents []*string `json:"tcpRetryEvents,omitempty" tf:"tcp_retry_events,omitempty"`
}

type HTTPRouteRetryPolicyParameters struct {

	// List of HTTP retry events.
	// Valid values: client-error (HTTP status code 409), gateway-error (HTTP status codes 502, 503, and 504), server-error (HTTP status codes 500, 501, 502, 503, 504, 505, 506, 507, 508, 510, and 511), stream-error (retry on refused stream).
	HTTPRetryEvents []*string `json:"httpRetryEvents,omitempty" tf:"http_retry_events,omitempty"`

	// Maximum number of retries.
	MaxRetries *float64 `json:"maxRetries,omitempty" tf:"max_retries,omitempty"`

	// Per-retry timeout.
	PerRetryTimeout []HTTPRouteRetryPolicyPerRetryTimeoutParameters `json:"perRetryTimeout,omitempty" tf:"per_retry_timeout,omitempty"`

	// List of TCP retry events. The only valid value is connection-error.
	TCPRetryEvents []*string `json:"tcpRetryEvents,omitempty" tf:"tcp_retry_events,omitempty"`
}

type HTTPRouteRetryPolicyPerRetryTimeoutInitParameters struct {

	// Unit of time. Valid values: ms, s.
	Unit *string `json:"unit,omitempty" tf:"unit,omitempty"`

	// Number of time units. Minimum value of 0.
	Value *float64 `json:"value,omitempty" tf:"value,omitempty"`
}

type HTTPRouteRetryPolicyPerRetryTimeoutObservation struct {

	// Unit of time. Valid values: ms, s.
	Unit *string `json:"unit,omitempty" tf:"unit,omitempty"`

	// Number of time units. Minimum value of 0.
	Value *float64 `json:"value,omitempty" tf:"value,omitempty"`
}

type HTTPRouteRetryPolicyPerRetryTimeoutParameters struct {

	// Unit of time. Valid values: ms, s.
	Unit *string `json:"unit,omitempty" tf:"unit,omitempty"`

	// Number of time units. Minimum value of 0.
	Value *float64 `json:"value,omitempty" tf:"value,omitempty"`
}

type HTTPRouteTimeoutIdleInitParameters struct {

	// Unit of time. Valid values: ms, s.
	Unit *string `json:"unit,omitempty" tf:"unit,omitempty"`

	// Number of time units. Minimum value of 0.
	Value *float64 `json:"value,omitempty" tf:"value,omitempty"`
}

type HTTPRouteTimeoutIdleObservation struct {

	// Unit of time. Valid values: ms, s.
	Unit *string `json:"unit,omitempty" tf:"unit,omitempty"`

	// Number of time units. Minimum value of 0.
	Value *float64 `json:"value,omitempty" tf:"value,omitempty"`
}

type HTTPRouteTimeoutIdleParameters struct {

	// Unit of time. Valid values: ms, s.
	Unit *string `json:"unit,omitempty" tf:"unit,omitempty"`

	// Number of time units. Minimum value of 0.
	Value *float64 `json:"value,omitempty" tf:"value,omitempty"`
}

type HTTPRouteTimeoutInitParameters struct {

	// Idle timeout. An idle timeout bounds the amount of time that a connection may be idle.
	Idle []HTTPRouteTimeoutIdleInitParameters `json:"idle,omitempty" tf:"idle,omitempty"`

	// Per request timeout.
	PerRequest []HTTPRouteTimeoutPerRequestInitParameters `json:"perRequest,omitempty" tf:"per_request,omitempty"`
}

type HTTPRouteTimeoutObservation struct {

	// Idle timeout. An idle timeout bounds the amount of time that a connection may be idle.
	Idle []HTTPRouteTimeoutIdleObservation `json:"idle,omitempty" tf:"idle,omitempty"`

	// Per request timeout.
	PerRequest []HTTPRouteTimeoutPerRequestObservation `json:"perRequest,omitempty" tf:"per_request,omitempty"`
}

type HTTPRouteTimeoutParameters struct {

	// Idle timeout. An idle timeout bounds the amount of time that a connection may be idle.
	Idle []HTTPRouteTimeoutIdleParameters `json:"idle,omitempty" tf:"idle,omitempty"`

	// Per request timeout.
	PerRequest []HTTPRouteTimeoutPerRequestParameters `json:"perRequest,omitempty" tf:"per_request,omitempty"`
}

type HTTPRouteTimeoutPerRequestInitParameters struct {

	// Unit of time. Valid values: ms, s.
	Unit *string `json:"unit,omitempty" tf:"unit,omitempty"`

	// Number of time units. Minimum value of 0.
	Value *float64 `json:"value,omitempty" tf:"value,omitempty"`
}

type HTTPRouteTimeoutPerRequestObservation struct {

	// Unit of time. Valid values: ms, s.
	Unit *string `json:"unit,omitempty" tf:"unit,omitempty"`

	// Number of time units. Minimum value of 0.
	Value *float64 `json:"value,omitempty" tf:"value,omitempty"`
}

type HTTPRouteTimeoutPerRequestParameters struct {

	// Unit of time. Valid values: ms, s.
	Unit *string `json:"unit,omitempty" tf:"unit,omitempty"`

	// Number of time units. Minimum value of 0.
	Value *float64 `json:"value,omitempty" tf:"value,omitempty"`
}

type HeaderInitParameters struct {

	// If true, the match is on the opposite of the match criteria. Default is false.
	Invert *bool `json:"invert,omitempty" tf:"invert,omitempty"`

	// Criteria for determining an gRPC request match.
	Match []HeaderMatchInitParameters `json:"match,omitempty" tf:"match,omitempty"`

	// Name to use for the route. Must be between 1 and 255 characters in length.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type HeaderMatchInitParameters struct {

	// Value sent by the client must match the specified value exactly. Must be between 1 and 255 characters in length.
	Exact *string `json:"exact,omitempty" tf:"exact,omitempty"`

	// Value sent by the client must begin with the specified characters. Must be between 1 and 255 characters in length.
	Prefix *string `json:"prefix,omitempty" tf:"prefix,omitempty"`

	// Object that specifies the range of numbers that the value sent by the client must be included in.
	Range []MatchRangeInitParameters `json:"range,omitempty" tf:"range,omitempty"`

	// Value sent by the client must include the specified characters. Must be between 1 and 255 characters in length.
	Regex *string `json:"regex,omitempty" tf:"regex,omitempty"`

	// Value sent by the client must end with the specified characters. Must be between 1 and 255 characters in length.
	Suffix *string `json:"suffix,omitempty" tf:"suffix,omitempty"`
}

type HeaderMatchObservation struct {

	// Value sent by the client must match the specified value exactly. Must be between 1 and 255 characters in length.
	Exact *string `json:"exact,omitempty" tf:"exact,omitempty"`

	// Value sent by the client must begin with the specified characters. Must be between 1 and 255 characters in length.
	Prefix *string `json:"prefix,omitempty" tf:"prefix,omitempty"`

	// Object that specifies the range of numbers that the value sent by the client must be included in.
	Range []MatchRangeObservation `json:"range,omitempty" tf:"range,omitempty"`

	// Value sent by the client must include the specified characters. Must be between 1 and 255 characters in length.
	Regex *string `json:"regex,omitempty" tf:"regex,omitempty"`

	// Value sent by the client must end with the specified characters. Must be between 1 and 255 characters in length.
	Suffix *string `json:"suffix,omitempty" tf:"suffix,omitempty"`
}

type HeaderMatchParameters struct {

	// Value sent by the client must match the specified value exactly. Must be between 1 and 255 characters in length.
	Exact *string `json:"exact,omitempty" tf:"exact,omitempty"`

	// Value sent by the client must begin with the specified characters. Must be between 1 and 255 characters in length.
	Prefix *string `json:"prefix,omitempty" tf:"prefix,omitempty"`

	// Object that specifies the range of numbers that the value sent by the client must be included in.
	Range []MatchRangeParameters `json:"range,omitempty" tf:"range,omitempty"`

	// Value sent by the client must include the specified characters. Must be between 1 and 255 characters in length.
	Regex *string `json:"regex,omitempty" tf:"regex,omitempty"`

	// Value sent by the client must end with the specified characters. Must be between 1 and 255 characters in length.
	Suffix *string `json:"suffix,omitempty" tf:"suffix,omitempty"`
}

type HeaderMatchRangeInitParameters struct {

	// End of the range.
	End *float64 `json:"end,omitempty" tf:"end,omitempty"`

	// (Requited) Start of the range.
	Start *float64 `json:"start,omitempty" tf:"start,omitempty"`
}

type HeaderMatchRangeObservation struct {

	// End of the range.
	End *float64 `json:"end,omitempty" tf:"end,omitempty"`

	// (Requited) Start of the range.
	Start *float64 `json:"start,omitempty" tf:"start,omitempty"`
}

type HeaderMatchRangeParameters struct {

	// End of the range.
	End *float64 `json:"end,omitempty" tf:"end,omitempty"`

	// (Requited) Start of the range.
	Start *float64 `json:"start,omitempty" tf:"start,omitempty"`
}

type HeaderObservation struct {

	// If true, the match is on the opposite of the match criteria. Default is false.
	Invert *bool `json:"invert,omitempty" tf:"invert,omitempty"`

	// Criteria for determining an gRPC request match.
	Match []HeaderMatchObservation `json:"match,omitempty" tf:"match,omitempty"`

	// Name to use for the route. Must be between 1 and 255 characters in length.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type HeaderParameters struct {

	// If true, the match is on the opposite of the match criteria. Default is false.
	Invert *bool `json:"invert,omitempty" tf:"invert,omitempty"`

	// Criteria for determining an gRPC request match.
	Match []HeaderMatchParameters `json:"match,omitempty" tf:"match,omitempty"`

	// Name to use for the route. Must be between 1 and 255 characters in length.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type Http2RouteRetryPolicyInitParameters struct {

	// List of HTTP retry events.
	// Valid values: client-error (HTTP status code 409), gateway-error (HTTP status codes 502, 503, and 504), server-error (HTTP status codes 500, 501, 502, 503, 504, 505, 506, 507, 508, 510, and 511), stream-error (retry on refused stream).
	HTTPRetryEvents []*string `json:"httpRetryEvents,omitempty" tf:"http_retry_events,omitempty"`

	// Maximum number of retries.
	MaxRetries *float64 `json:"maxRetries,omitempty" tf:"max_retries,omitempty"`

	// Per-retry timeout.
	PerRetryTimeout []RetryPolicyPerRetryTimeoutInitParameters `json:"perRetryTimeout,omitempty" tf:"per_retry_timeout,omitempty"`

	// List of TCP retry events. The only valid value is connection-error.
	TCPRetryEvents []*string `json:"tcpRetryEvents,omitempty" tf:"tcp_retry_events,omitempty"`
}

type Http2RouteRetryPolicyObservation struct {

	// List of HTTP retry events.
	// Valid values: client-error (HTTP status code 409), gateway-error (HTTP status codes 502, 503, and 504), server-error (HTTP status codes 500, 501, 502, 503, 504, 505, 506, 507, 508, 510, and 511), stream-error (retry on refused stream).
	HTTPRetryEvents []*string `json:"httpRetryEvents,omitempty" tf:"http_retry_events,omitempty"`

	// Maximum number of retries.
	MaxRetries *float64 `json:"maxRetries,omitempty" tf:"max_retries,omitempty"`

	// Per-retry timeout.
	PerRetryTimeout []RetryPolicyPerRetryTimeoutObservation `json:"perRetryTimeout,omitempty" tf:"per_retry_timeout,omitempty"`

	// List of TCP retry events. The only valid value is connection-error.
	TCPRetryEvents []*string `json:"tcpRetryEvents,omitempty" tf:"tcp_retry_events,omitempty"`
}

type Http2RouteRetryPolicyParameters struct {

	// List of HTTP retry events.
	// Valid values: client-error (HTTP status code 409), gateway-error (HTTP status codes 502, 503, and 504), server-error (HTTP status codes 500, 501, 502, 503, 504, 505, 506, 507, 508, 510, and 511), stream-error (retry on refused stream).
	HTTPRetryEvents []*string `json:"httpRetryEvents,omitempty" tf:"http_retry_events,omitempty"`

	// Maximum number of retries.
	MaxRetries *float64 `json:"maxRetries,omitempty" tf:"max_retries,omitempty"`

	// Per-retry timeout.
	PerRetryTimeout []RetryPolicyPerRetryTimeoutParameters `json:"perRetryTimeout,omitempty" tf:"per_retry_timeout,omitempty"`

	// List of TCP retry events. The only valid value is connection-error.
	TCPRetryEvents []*string `json:"tcpRetryEvents,omitempty" tf:"tcp_retry_events,omitempty"`
}

type Http2RouteTimeoutInitParameters struct {

	// Idle timeout. An idle timeout bounds the amount of time that a connection may be idle.
	Idle []TimeoutIdleInitParameters `json:"idle,omitempty" tf:"idle,omitempty"`

	// Per request timeout.
	PerRequest []TimeoutPerRequestInitParameters `json:"perRequest,omitempty" tf:"per_request,omitempty"`
}

type Http2RouteTimeoutObservation struct {

	// Idle timeout. An idle timeout bounds the amount of time that a connection may be idle.
	Idle []TimeoutIdleObservation `json:"idle,omitempty" tf:"idle,omitempty"`

	// Per request timeout.
	PerRequest []TimeoutPerRequestObservation `json:"perRequest,omitempty" tf:"per_request,omitempty"`
}

type Http2RouteTimeoutParameters struct {

	// Idle timeout. An idle timeout bounds the amount of time that a connection may be idle.
	Idle []TimeoutIdleParameters `json:"idle,omitempty" tf:"idle,omitempty"`

	// Per request timeout.
	PerRequest []TimeoutPerRequestParameters `json:"perRequest,omitempty" tf:"per_request,omitempty"`
}

type IdleInitParameters struct {

	// Unit of time. Valid values: ms, s.
	Unit *string `json:"unit,omitempty" tf:"unit,omitempty"`

	// Number of time units. Minimum value of 0.
	Value *float64 `json:"value,omitempty" tf:"value,omitempty"`
}

type IdleObservation struct {

	// Unit of time. Valid values: ms, s.
	Unit *string `json:"unit,omitempty" tf:"unit,omitempty"`

	// Number of time units. Minimum value of 0.
	Value *float64 `json:"value,omitempty" tf:"value,omitempty"`
}

type IdleParameters struct {

	// Unit of time. Valid values: ms, s.
	Unit *string `json:"unit,omitempty" tf:"unit,omitempty"`

	// Number of time units. Minimum value of 0.
	Value *float64 `json:"value,omitempty" tf:"value,omitempty"`
}

type MatchHeaderInitParameters struct {

	// If true, the match is on the opposite of the match criteria. Default is false.
	Invert *bool `json:"invert,omitempty" tf:"invert,omitempty"`

	// Criteria for determining an gRPC request match.
	Match []MatchHeaderMatchInitParameters `json:"match,omitempty" tf:"match,omitempty"`

	// Name to use for the route. Must be between 1 and 255 characters in length.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type MatchHeaderMatchInitParameters struct {

	// Value sent by the client must match the specified value exactly. Must be between 1 and 255 characters in length.
	Exact *string `json:"exact,omitempty" tf:"exact,omitempty"`

	// Value sent by the client must begin with the specified characters. Must be between 1 and 255 characters in length.
	Prefix *string `json:"prefix,omitempty" tf:"prefix,omitempty"`

	// Object that specifies the range of numbers that the value sent by the client must be included in.
	Range []HeaderMatchRangeInitParameters `json:"range,omitempty" tf:"range,omitempty"`

	// Value sent by the client must include the specified characters. Must be between 1 and 255 characters in length.
	Regex *string `json:"regex,omitempty" tf:"regex,omitempty"`

	// Value sent by the client must end with the specified characters. Must be between 1 and 255 characters in length.
	Suffix *string `json:"suffix,omitempty" tf:"suffix,omitempty"`
}

type MatchHeaderMatchObservation struct {

	// Value sent by the client must match the specified value exactly. Must be between 1 and 255 characters in length.
	Exact *string `json:"exact,omitempty" tf:"exact,omitempty"`

	// Value sent by the client must begin with the specified characters. Must be between 1 and 255 characters in length.
	Prefix *string `json:"prefix,omitempty" tf:"prefix,omitempty"`

	// Object that specifies the range of numbers that the value sent by the client must be included in.
	Range []HeaderMatchRangeObservation `json:"range,omitempty" tf:"range,omitempty"`

	// Value sent by the client must include the specified characters. Must be between 1 and 255 characters in length.
	Regex *string `json:"regex,omitempty" tf:"regex,omitempty"`

	// Value sent by the client must end with the specified characters. Must be between 1 and 255 characters in length.
	Suffix *string `json:"suffix,omitempty" tf:"suffix,omitempty"`
}

type MatchHeaderMatchParameters struct {

	// Value sent by the client must match the specified value exactly. Must be between 1 and 255 characters in length.
	Exact *string `json:"exact,omitempty" tf:"exact,omitempty"`

	// Value sent by the client must begin with the specified characters. Must be between 1 and 255 characters in length.
	Prefix *string `json:"prefix,omitempty" tf:"prefix,omitempty"`

	// Object that specifies the range of numbers that the value sent by the client must be included in.
	Range []HeaderMatchRangeParameters `json:"range,omitempty" tf:"range,omitempty"`

	// Value sent by the client must include the specified characters. Must be between 1 and 255 characters in length.
	Regex *string `json:"regex,omitempty" tf:"regex,omitempty"`

	// Value sent by the client must end with the specified characters. Must be between 1 and 255 characters in length.
	Suffix *string `json:"suffix,omitempty" tf:"suffix,omitempty"`
}

type MatchHeaderObservation struct {

	// If true, the match is on the opposite of the match criteria. Default is false.
	Invert *bool `json:"invert,omitempty" tf:"invert,omitempty"`

	// Criteria for determining an gRPC request match.
	Match []MatchHeaderMatchObservation `json:"match,omitempty" tf:"match,omitempty"`

	// Name to use for the route. Must be between 1 and 255 characters in length.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type MatchHeaderParameters struct {

	// If true, the match is on the opposite of the match criteria. Default is false.
	Invert *bool `json:"invert,omitempty" tf:"invert,omitempty"`

	// Criteria for determining an gRPC request match.
	Match []MatchHeaderMatchParameters `json:"match,omitempty" tf:"match,omitempty"`

	// Name to use for the route. Must be between 1 and 255 characters in length.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type MatchRangeInitParameters struct {

	// End of the range.
	End *float64 `json:"end,omitempty" tf:"end,omitempty"`

	// (Requited) Start of the range.
	Start *float64 `json:"start,omitempty" tf:"start,omitempty"`
}

type MatchRangeObservation struct {

	// End of the range.
	End *float64 `json:"end,omitempty" tf:"end,omitempty"`

	// (Requited) Start of the range.
	Start *float64 `json:"start,omitempty" tf:"start,omitempty"`
}

type MatchRangeParameters struct {

	// End of the range.
	End *float64 `json:"end,omitempty" tf:"end,omitempty"`

	// (Requited) Start of the range.
	Start *float64 `json:"start,omitempty" tf:"start,omitempty"`
}

type MetadataInitParameters struct {

	// If true, the match is on the opposite of the match criteria. Default is false.
	Invert *bool `json:"invert,omitempty" tf:"invert,omitempty"`

	// Criteria for determining an gRPC request match.
	Match []MetadataMatchInitParameters `json:"match,omitempty" tf:"match,omitempty"`

	// Name to use for the route. Must be between 1 and 255 characters in length.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type MetadataMatchInitParameters struct {

	// Value sent by the client must match the specified value exactly. Must be between 1 and 255 characters in length.
	Exact *string `json:"exact,omitempty" tf:"exact,omitempty"`

	// Value sent by the client must begin with the specified characters. Must be between 1 and 255 characters in length.
	Prefix *string `json:"prefix,omitempty" tf:"prefix,omitempty"`

	// Object that specifies the range of numbers that the value sent by the client must be included in.
	Range []RangeInitParameters `json:"range,omitempty" tf:"range,omitempty"`

	// Value sent by the client must include the specified characters. Must be between 1 and 255 characters in length.
	Regex *string `json:"regex,omitempty" tf:"regex,omitempty"`

	// Value sent by the client must end with the specified characters. Must be between 1 and 255 characters in length.
	Suffix *string `json:"suffix,omitempty" tf:"suffix,omitempty"`
}

type MetadataMatchObservation struct {

	// Value sent by the client must match the specified value exactly. Must be between 1 and 255 characters in length.
	Exact *string `json:"exact,omitempty" tf:"exact,omitempty"`

	// Value sent by the client must begin with the specified characters. Must be between 1 and 255 characters in length.
	Prefix *string `json:"prefix,omitempty" tf:"prefix,omitempty"`

	// Object that specifies the range of numbers that the value sent by the client must be included in.
	Range []RangeObservation `json:"range,omitempty" tf:"range,omitempty"`

	// Value sent by the client must include the specified characters. Must be between 1 and 255 characters in length.
	Regex *string `json:"regex,omitempty" tf:"regex,omitempty"`

	// Value sent by the client must end with the specified characters. Must be between 1 and 255 characters in length.
	Suffix *string `json:"suffix,omitempty" tf:"suffix,omitempty"`
}

type MetadataMatchParameters struct {

	// Value sent by the client must match the specified value exactly. Must be between 1 and 255 characters in length.
	Exact *string `json:"exact,omitempty" tf:"exact,omitempty"`

	// Value sent by the client must begin with the specified characters. Must be between 1 and 255 characters in length.
	Prefix *string `json:"prefix,omitempty" tf:"prefix,omitempty"`

	// Object that specifies the range of numbers that the value sent by the client must be included in.
	Range []RangeParameters `json:"range,omitempty" tf:"range,omitempty"`

	// Value sent by the client must include the specified characters. Must be between 1 and 255 characters in length.
	Regex *string `json:"regex,omitempty" tf:"regex,omitempty"`

	// Value sent by the client must end with the specified characters. Must be between 1 and 255 characters in length.
	Suffix *string `json:"suffix,omitempty" tf:"suffix,omitempty"`
}

type MetadataObservation struct {

	// If true, the match is on the opposite of the match criteria. Default is false.
	Invert *bool `json:"invert,omitempty" tf:"invert,omitempty"`

	// Criteria for determining an gRPC request match.
	Match []MetadataMatchObservation `json:"match,omitempty" tf:"match,omitempty"`

	// Name to use for the route. Must be between 1 and 255 characters in length.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type MetadataParameters struct {

	// If true, the match is on the opposite of the match criteria. Default is false.
	Invert *bool `json:"invert,omitempty" tf:"invert,omitempty"`

	// Criteria for determining an gRPC request match.
	Match []MetadataMatchParameters `json:"match,omitempty" tf:"match,omitempty"`

	// Name to use for the route. Must be between 1 and 255 characters in length.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type PerRequestInitParameters struct {

	// Unit of time. Valid values: ms, s.
	Unit *string `json:"unit,omitempty" tf:"unit,omitempty"`

	// Number of time units. Minimum value of 0.
	Value *float64 `json:"value,omitempty" tf:"value,omitempty"`
}

type PerRequestObservation struct {

	// Unit of time. Valid values: ms, s.
	Unit *string `json:"unit,omitempty" tf:"unit,omitempty"`

	// Number of time units. Minimum value of 0.
	Value *float64 `json:"value,omitempty" tf:"value,omitempty"`
}

type PerRequestParameters struct {

	// Unit of time. Valid values: ms, s.
	Unit *string `json:"unit,omitempty" tf:"unit,omitempty"`

	// Number of time units. Minimum value of 0.
	Value *float64 `json:"value,omitempty" tf:"value,omitempty"`
}

type PerRetryTimeoutInitParameters struct {

	// Unit of time. Valid values: ms, s.
	Unit *string `json:"unit,omitempty" tf:"unit,omitempty"`

	// Number of time units. Minimum value of 0.
	Value *float64 `json:"value,omitempty" tf:"value,omitempty"`
}

type PerRetryTimeoutObservation struct {

	// Unit of time. Valid values: ms, s.
	Unit *string `json:"unit,omitempty" tf:"unit,omitempty"`

	// Number of time units. Minimum value of 0.
	Value *float64 `json:"value,omitempty" tf:"value,omitempty"`
}

type PerRetryTimeoutParameters struct {

	// Unit of time. Valid values: ms, s.
	Unit *string `json:"unit,omitempty" tf:"unit,omitempty"`

	// Number of time units. Minimum value of 0.
	Value *float64 `json:"value,omitempty" tf:"value,omitempty"`
}

type RangeInitParameters struct {

	// End of the range.
	End *float64 `json:"end,omitempty" tf:"end,omitempty"`

	// (Requited) Start of the range.
	Start *float64 `json:"start,omitempty" tf:"start,omitempty"`
}

type RangeObservation struct {

	// End of the range.
	End *float64 `json:"end,omitempty" tf:"end,omitempty"`

	// (Requited) Start of the range.
	Start *float64 `json:"start,omitempty" tf:"start,omitempty"`
}

type RangeParameters struct {

	// End of the range.
	End *float64 `json:"end,omitempty" tf:"end,omitempty"`

	// (Requited) Start of the range.
	Start *float64 `json:"start,omitempty" tf:"start,omitempty"`
}

type RetryPolicyInitParameters struct {

	// List of gRPC retry events.
	// Valid values: cancelled, deadline-exceeded, internal, resource-exhausted, unavailable.
	GRPCRetryEvents []*string `json:"grpcRetryEvents,omitempty" tf:"grpc_retry_events,omitempty"`

	// List of HTTP retry events.
	// Valid values: client-error (HTTP status code 409), gateway-error (HTTP status codes 502, 503, and 504), server-error (HTTP status codes 500, 501, 502, 503, 504, 505, 506, 507, 508, 510, and 511), stream-error (retry on refused stream).
	HTTPRetryEvents []*string `json:"httpRetryEvents,omitempty" tf:"http_retry_events,omitempty"`

	// Maximum number of retries.
	MaxRetries *float64 `json:"maxRetries,omitempty" tf:"max_retries,omitempty"`

	// Per-retry timeout.
	PerRetryTimeout []PerRetryTimeoutInitParameters `json:"perRetryTimeout,omitempty" tf:"per_retry_timeout,omitempty"`

	// List of TCP retry events. The only valid value is connection-error.
	TCPRetryEvents []*string `json:"tcpRetryEvents,omitempty" tf:"tcp_retry_events,omitempty"`
}

type RetryPolicyObservation struct {

	// List of gRPC retry events.
	// Valid values: cancelled, deadline-exceeded, internal, resource-exhausted, unavailable.
	GRPCRetryEvents []*string `json:"grpcRetryEvents,omitempty" tf:"grpc_retry_events,omitempty"`

	// List of HTTP retry events.
	// Valid values: client-error (HTTP status code 409), gateway-error (HTTP status codes 502, 503, and 504), server-error (HTTP status codes 500, 501, 502, 503, 504, 505, 506, 507, 508, 510, and 511), stream-error (retry on refused stream).
	HTTPRetryEvents []*string `json:"httpRetryEvents,omitempty" tf:"http_retry_events,omitempty"`

	// Maximum number of retries.
	MaxRetries *float64 `json:"maxRetries,omitempty" tf:"max_retries,omitempty"`

	// Per-retry timeout.
	PerRetryTimeout []PerRetryTimeoutObservation `json:"perRetryTimeout,omitempty" tf:"per_retry_timeout,omitempty"`

	// List of TCP retry events. The only valid value is connection-error.
	TCPRetryEvents []*string `json:"tcpRetryEvents,omitempty" tf:"tcp_retry_events,omitempty"`
}

type RetryPolicyParameters struct {

	// List of gRPC retry events.
	// Valid values: cancelled, deadline-exceeded, internal, resource-exhausted, unavailable.
	GRPCRetryEvents []*string `json:"grpcRetryEvents,omitempty" tf:"grpc_retry_events,omitempty"`

	// List of HTTP retry events.
	// Valid values: client-error (HTTP status code 409), gateway-error (HTTP status codes 502, 503, and 504), server-error (HTTP status codes 500, 501, 502, 503, 504, 505, 506, 507, 508, 510, and 511), stream-error (retry on refused stream).
	HTTPRetryEvents []*string `json:"httpRetryEvents,omitempty" tf:"http_retry_events,omitempty"`

	// Maximum number of retries.
	MaxRetries *float64 `json:"maxRetries,omitempty" tf:"max_retries,omitempty"`

	// Per-retry timeout.
	PerRetryTimeout []PerRetryTimeoutParameters `json:"perRetryTimeout,omitempty" tf:"per_retry_timeout,omitempty"`

	// List of TCP retry events. The only valid value is connection-error.
	TCPRetryEvents []*string `json:"tcpRetryEvents,omitempty" tf:"tcp_retry_events,omitempty"`
}

type RetryPolicyPerRetryTimeoutInitParameters struct {

	// Unit of time. Valid values: ms, s.
	Unit *string `json:"unit,omitempty" tf:"unit,omitempty"`

	// Number of time units. Minimum value of 0.
	Value *float64 `json:"value,omitempty" tf:"value,omitempty"`
}

type RetryPolicyPerRetryTimeoutObservation struct {

	// Unit of time. Valid values: ms, s.
	Unit *string `json:"unit,omitempty" tf:"unit,omitempty"`

	// Number of time units. Minimum value of 0.
	Value *float64 `json:"value,omitempty" tf:"value,omitempty"`
}

type RetryPolicyPerRetryTimeoutParameters struct {

	// Unit of time. Valid values: ms, s.
	Unit *string `json:"unit,omitempty" tf:"unit,omitempty"`

	// Number of time units. Minimum value of 0.
	Value *float64 `json:"value,omitempty" tf:"value,omitempty"`
}

type RouteInitParameters struct {

	// Name of the service mesh in which to create the route. Must be between 1 and 255 characters in length.
	// +crossplane:generate:reference:type=github.com/upbound/provider-aws/apis/appmesh/v1beta1.Mesh
	// +crossplane:generate:reference:extractor=github.com/upbound/upjet/pkg/resource.ExtractResourceID()
	MeshName *string `json:"meshName,omitempty" tf:"mesh_name,omitempty"`

	MeshNameRef *v1.Reference `json:"meshNameRef,omitempty" tf:"-"`

	MeshNameSelector *v1.Selector `json:"meshNameSelector,omitempty" tf:"-"`

	// AWS account ID of the service mesh's owner. Defaults to the account ID the AWS provider is currently connected to.
	MeshOwner *string `json:"meshOwner,omitempty" tf:"mesh_owner,omitempty"`

	// Name to use for the route. Must be between 1 and 255 characters in length.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Region is the region you'd like your resource to be created in.
	// +upjet:crd:field:TFTag=-
	Region *string `json:"region,omitempty" tf:"-"`

	// Route specification to apply.
	Spec []RouteSpecInitParameters `json:"spec,omitempty" tf:"spec,omitempty"`

	// Key-value map of resource tags.
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// Name of the virtual router in which to create the route. Must be between 1 and 255 characters in length.
	// +crossplane:generate:reference:type=github.com/upbound/provider-aws/apis/appmesh/v1beta1.VirtualRouter
	// +crossplane:generate:reference:extractor=github.com/upbound/upjet/pkg/resource.ExtractParamPath("name",false)
	VirtualRouterName *string `json:"virtualRouterName,omitempty" tf:"virtual_router_name,omitempty"`

	VirtualRouterNameRef *v1.Reference `json:"virtualRouterNameRef,omitempty" tf:"-"`

	VirtualRouterNameSelector *v1.Selector `json:"virtualRouterNameSelector,omitempty" tf:"-"`
}

type RouteObservation struct {

	// ARN of the route.
	Arn *string `json:"arn,omitempty" tf:"arn,omitempty"`

	// Creation date of the route.
	CreatedDate *string `json:"createdDate,omitempty" tf:"created_date,omitempty"`

	// ID of the route.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Last update date of the route.
	LastUpdatedDate *string `json:"lastUpdatedDate,omitempty" tf:"last_updated_date,omitempty"`

	// Name of the service mesh in which to create the route. Must be between 1 and 255 characters in length.
	MeshName *string `json:"meshName,omitempty" tf:"mesh_name,omitempty"`

	// AWS account ID of the service mesh's owner. Defaults to the account ID the AWS provider is currently connected to.
	MeshOwner *string `json:"meshOwner,omitempty" tf:"mesh_owner,omitempty"`

	// Name to use for the route. Must be between 1 and 255 characters in length.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Resource owner's AWS account ID.
	ResourceOwner *string `json:"resourceOwner,omitempty" tf:"resource_owner,omitempty"`

	// Route specification to apply.
	Spec []RouteSpecObservation `json:"spec,omitempty" tf:"spec,omitempty"`

	// Key-value map of resource tags.
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// Map of tags assigned to the resource, including those inherited from the provider default_tags configuration block.
	TagsAll map[string]*string `json:"tagsAll,omitempty" tf:"tags_all,omitempty"`

	// Name of the virtual router in which to create the route. Must be between 1 and 255 characters in length.
	VirtualRouterName *string `json:"virtualRouterName,omitempty" tf:"virtual_router_name,omitempty"`
}

type RouteParameters struct {

	// Name of the service mesh in which to create the route. Must be between 1 and 255 characters in length.
	// +crossplane:generate:reference:type=github.com/upbound/provider-aws/apis/appmesh/v1beta1.Mesh
	// +crossplane:generate:reference:extractor=github.com/upbound/upjet/pkg/resource.ExtractResourceID()
	MeshName *string `json:"meshName,omitempty" tf:"mesh_name,omitempty"`

	// Reference to a Mesh in appmesh to populate meshName.
	// +kubebuilder:validation:Optional
	MeshNameRef *v1.Reference `json:"meshNameRef,omitempty" tf:"-"`

	// Selector for a Mesh in appmesh to populate meshName.
	// +kubebuilder:validation:Optional
	MeshNameSelector *v1.Selector `json:"meshNameSelector,omitempty" tf:"-"`

	// AWS account ID of the service mesh's owner. Defaults to the account ID the AWS provider is currently connected to.
	MeshOwner *string `json:"meshOwner,omitempty" tf:"mesh_owner,omitempty"`

	// Name to use for the route. Must be between 1 and 255 characters in length.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Region is the region you'd like your resource to be created in.
	// +upjet:crd:field:TFTag=-
	Region *string `json:"region,omitempty" tf:"-"`

	// Route specification to apply.
	Spec []RouteSpecParameters `json:"spec,omitempty" tf:"spec,omitempty"`

	// Key-value map of resource tags.
	Tags map[string]*string `json:"tags,omitempty" tf:"tags,omitempty"`

	// Name of the virtual router in which to create the route. Must be between 1 and 255 characters in length.
	// +crossplane:generate:reference:type=github.com/upbound/provider-aws/apis/appmesh/v1beta1.VirtualRouter
	// +crossplane:generate:reference:extractor=github.com/upbound/upjet/pkg/resource.ExtractParamPath("name",false)
	VirtualRouterName *string `json:"virtualRouterName,omitempty" tf:"virtual_router_name,omitempty"`

	// Reference to a VirtualRouter in appmesh to populate virtualRouterName.
	// +kubebuilder:validation:Optional
	VirtualRouterNameRef *v1.Reference `json:"virtualRouterNameRef,omitempty" tf:"-"`

	// Selector for a VirtualRouter in appmesh to populate virtualRouterName.
	// +kubebuilder:validation:Optional
	VirtualRouterNameSelector *v1.Selector `json:"virtualRouterNameSelector,omitempty" tf:"-"`
}

type RouteSpecInitParameters struct {

	// GRPC routing information for the route.
	GRPCRoute []SpecGRPCRouteInitParameters `json:"grpcRoute,omitempty" tf:"grpc_route,omitempty"`

	// HTTP routing information for the route.
	HTTPRoute []SpecHTTPRouteInitParameters `json:"httpRoute,omitempty" tf:"http_route,omitempty"`

	// HTTP/2 routing information for the route.
	Http2Route []SpecHttp2RouteInitParameters `json:"http2Route,omitempty" tf:"http2_route,omitempty"`

	// Priority for the route, between 0 and 1000.
	// Routes are matched based on the specified value, where 0 is the highest priority.
	Priority *float64 `json:"priority,omitempty" tf:"priority,omitempty"`

	// TCP routing information for the route.
	TCPRoute []TCPRouteInitParameters `json:"tcpRoute,omitempty" tf:"tcp_route,omitempty"`
}

type RouteSpecObservation struct {

	// GRPC routing information for the route.
	GRPCRoute []SpecGRPCRouteObservation `json:"grpcRoute,omitempty" tf:"grpc_route,omitempty"`

	// HTTP routing information for the route.
	HTTPRoute []SpecHTTPRouteObservation `json:"httpRoute,omitempty" tf:"http_route,omitempty"`

	// HTTP/2 routing information for the route.
	Http2Route []SpecHttp2RouteObservation `json:"http2Route,omitempty" tf:"http2_route,omitempty"`

	// Priority for the route, between 0 and 1000.
	// Routes are matched based on the specified value, where 0 is the highest priority.
	Priority *float64 `json:"priority,omitempty" tf:"priority,omitempty"`

	// TCP routing information for the route.
	TCPRoute []TCPRouteObservation `json:"tcpRoute,omitempty" tf:"tcp_route,omitempty"`
}

type RouteSpecParameters struct {

	// GRPC routing information for the route.
	GRPCRoute []SpecGRPCRouteParameters `json:"grpcRoute,omitempty" tf:"grpc_route,omitempty"`

	// HTTP routing information for the route.
	HTTPRoute []SpecHTTPRouteParameters `json:"httpRoute,omitempty" tf:"http_route,omitempty"`

	// HTTP/2 routing information for the route.
	Http2Route []SpecHttp2RouteParameters `json:"http2Route,omitempty" tf:"http2_route,omitempty"`

	// Priority for the route, between 0 and 1000.
	// Routes are matched based on the specified value, where 0 is the highest priority.
	Priority *float64 `json:"priority,omitempty" tf:"priority,omitempty"`

	// TCP routing information for the route.
	TCPRoute []TCPRouteParameters `json:"tcpRoute,omitempty" tf:"tcp_route,omitempty"`
}

type SpecGRPCRouteInitParameters struct {

	// Action to take if a match is determined.
	Action []GRPCRouteActionInitParameters `json:"action,omitempty" tf:"action,omitempty"`

	// Criteria for determining an gRPC request match.
	Match []GRPCRouteMatchInitParameters `json:"match,omitempty" tf:"match,omitempty"`

	// Retry policy.
	RetryPolicy []RetryPolicyInitParameters `json:"retryPolicy,omitempty" tf:"retry_policy,omitempty"`

	// Types of timeouts.
	Timeout []TimeoutInitParameters `json:"timeout,omitempty" tf:"timeout,omitempty"`
}

type SpecGRPCRouteObservation struct {

	// Action to take if a match is determined.
	Action []GRPCRouteActionObservation `json:"action,omitempty" tf:"action,omitempty"`

	// Criteria for determining an gRPC request match.
	Match []GRPCRouteMatchObservation `json:"match,omitempty" tf:"match,omitempty"`

	// Retry policy.
	RetryPolicy []RetryPolicyObservation `json:"retryPolicy,omitempty" tf:"retry_policy,omitempty"`

	// Types of timeouts.
	Timeout []TimeoutObservation `json:"timeout,omitempty" tf:"timeout,omitempty"`
}

type SpecGRPCRouteParameters struct {

	// Action to take if a match is determined.
	Action []GRPCRouteActionParameters `json:"action,omitempty" tf:"action,omitempty"`

	// Criteria for determining an gRPC request match.
	Match []GRPCRouteMatchParameters `json:"match,omitempty" tf:"match,omitempty"`

	// Retry policy.
	RetryPolicy []RetryPolicyParameters `json:"retryPolicy,omitempty" tf:"retry_policy,omitempty"`

	// Types of timeouts.
	Timeout []TimeoutParameters `json:"timeout,omitempty" tf:"timeout,omitempty"`
}

type SpecHTTPRouteActionInitParameters struct {

	// Targets that traffic is routed to when a request matches the route.
	// You can specify one or more targets and their relative weights with which to distribute traffic.
	WeightedTarget []HTTPRouteActionWeightedTargetInitParameters `json:"weightedTarget,omitempty" tf:"weighted_target,omitempty"`
}

type SpecHTTPRouteActionObservation struct {

	// Targets that traffic is routed to when a request matches the route.
	// You can specify one or more targets and their relative weights with which to distribute traffic.
	WeightedTarget []HTTPRouteActionWeightedTargetObservation `json:"weightedTarget,omitempty" tf:"weighted_target,omitempty"`
}

type SpecHTTPRouteActionParameters struct {

	// Targets that traffic is routed to when a request matches the route.
	// You can specify one or more targets and their relative weights with which to distribute traffic.
	WeightedTarget []HTTPRouteActionWeightedTargetParameters `json:"weightedTarget,omitempty" tf:"weighted_target,omitempty"`
}

type SpecHTTPRouteInitParameters struct {

	// Action to take if a match is determined.
	Action []SpecHTTPRouteActionInitParameters `json:"action,omitempty" tf:"action,omitempty"`

	// Criteria for determining an gRPC request match.
	Match []SpecHTTPRouteMatchInitParameters `json:"match,omitempty" tf:"match,omitempty"`

	// Retry policy.
	RetryPolicy []HTTPRouteRetryPolicyInitParameters `json:"retryPolicy,omitempty" tf:"retry_policy,omitempty"`

	// Types of timeouts.
	Timeout []HTTPRouteTimeoutInitParameters `json:"timeout,omitempty" tf:"timeout,omitempty"`
}

type SpecHTTPRouteMatchInitParameters struct {

	// Client request headers to match on.
	Header []MatchHeaderInitParameters `json:"header,omitempty" tf:"header,omitempty"`

	// Client request header method to match on. Valid values: GET, HEAD, POST, PUT, DELETE, CONNECT, OPTIONS, TRACE, PATCH.
	Method *string `json:"method,omitempty" tf:"method,omitempty"`

	// The port number to match from the request.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// Value sent by the client must begin with the specified characters. Must be between 1 and 255 characters in length.
	Prefix *string `json:"prefix,omitempty" tf:"prefix,omitempty"`

	// Client request header scheme to match on. Valid values: http, https.
	Scheme *string `json:"scheme,omitempty" tf:"scheme,omitempty"`
}

type SpecHTTPRouteMatchObservation struct {

	// Client request headers to match on.
	Header []MatchHeaderObservation `json:"header,omitempty" tf:"header,omitempty"`

	// Client request header method to match on. Valid values: GET, HEAD, POST, PUT, DELETE, CONNECT, OPTIONS, TRACE, PATCH.
	Method *string `json:"method,omitempty" tf:"method,omitempty"`

	// The port number to match from the request.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// Value sent by the client must begin with the specified characters. Must be between 1 and 255 characters in length.
	Prefix *string `json:"prefix,omitempty" tf:"prefix,omitempty"`

	// Client request header scheme to match on. Valid values: http, https.
	Scheme *string `json:"scheme,omitempty" tf:"scheme,omitempty"`
}

type SpecHTTPRouteMatchParameters struct {

	// Client request headers to match on.
	Header []MatchHeaderParameters `json:"header,omitempty" tf:"header,omitempty"`

	// Client request header method to match on. Valid values: GET, HEAD, POST, PUT, DELETE, CONNECT, OPTIONS, TRACE, PATCH.
	Method *string `json:"method,omitempty" tf:"method,omitempty"`

	// The port number to match from the request.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// Value sent by the client must begin with the specified characters. Must be between 1 and 255 characters in length.
	Prefix *string `json:"prefix,omitempty" tf:"prefix,omitempty"`

	// Client request header scheme to match on. Valid values: http, https.
	Scheme *string `json:"scheme,omitempty" tf:"scheme,omitempty"`
}

type SpecHTTPRouteObservation struct {

	// Action to take if a match is determined.
	Action []SpecHTTPRouteActionObservation `json:"action,omitempty" tf:"action,omitempty"`

	// Criteria for determining an gRPC request match.
	Match []SpecHTTPRouteMatchObservation `json:"match,omitempty" tf:"match,omitempty"`

	// Retry policy.
	RetryPolicy []HTTPRouteRetryPolicyObservation `json:"retryPolicy,omitempty" tf:"retry_policy,omitempty"`

	// Types of timeouts.
	Timeout []HTTPRouteTimeoutObservation `json:"timeout,omitempty" tf:"timeout,omitempty"`
}

type SpecHTTPRouteParameters struct {

	// Action to take if a match is determined.
	Action []SpecHTTPRouteActionParameters `json:"action,omitempty" tf:"action,omitempty"`

	// Criteria for determining an gRPC request match.
	Match []SpecHTTPRouteMatchParameters `json:"match,omitempty" tf:"match,omitempty"`

	// Retry policy.
	RetryPolicy []HTTPRouteRetryPolicyParameters `json:"retryPolicy,omitempty" tf:"retry_policy,omitempty"`

	// Types of timeouts.
	Timeout []HTTPRouteTimeoutParameters `json:"timeout,omitempty" tf:"timeout,omitempty"`
}

type SpecHttp2RouteActionInitParameters struct {

	// Targets that traffic is routed to when a request matches the route.
	// You can specify one or more targets and their relative weights with which to distribute traffic.
	WeightedTarget []ActionWeightedTargetInitParameters `json:"weightedTarget,omitempty" tf:"weighted_target,omitempty"`
}

type SpecHttp2RouteActionObservation struct {

	// Targets that traffic is routed to when a request matches the route.
	// You can specify one or more targets and their relative weights with which to distribute traffic.
	WeightedTarget []ActionWeightedTargetObservation `json:"weightedTarget,omitempty" tf:"weighted_target,omitempty"`
}

type SpecHttp2RouteActionParameters struct {

	// Targets that traffic is routed to when a request matches the route.
	// You can specify one or more targets and their relative weights with which to distribute traffic.
	WeightedTarget []ActionWeightedTargetParameters `json:"weightedTarget,omitempty" tf:"weighted_target,omitempty"`
}

type SpecHttp2RouteInitParameters struct {

	// Action to take if a match is determined.
	Action []SpecHttp2RouteActionInitParameters `json:"action,omitempty" tf:"action,omitempty"`

	// Criteria for determining an gRPC request match.
	Match []SpecHttp2RouteMatchInitParameters `json:"match,omitempty" tf:"match,omitempty"`

	// Retry policy.
	RetryPolicy []Http2RouteRetryPolicyInitParameters `json:"retryPolicy,omitempty" tf:"retry_policy,omitempty"`

	// Types of timeouts.
	Timeout []Http2RouteTimeoutInitParameters `json:"timeout,omitempty" tf:"timeout,omitempty"`
}

type SpecHttp2RouteMatchInitParameters struct {

	// Client request headers to match on.
	Header []HeaderInitParameters `json:"header,omitempty" tf:"header,omitempty"`

	// Client request header method to match on. Valid values: GET, HEAD, POST, PUT, DELETE, CONNECT, OPTIONS, TRACE, PATCH.
	Method *string `json:"method,omitempty" tf:"method,omitempty"`

	// The port number to match from the request.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// Value sent by the client must begin with the specified characters. Must be between 1 and 255 characters in length.
	Prefix *string `json:"prefix,omitempty" tf:"prefix,omitempty"`

	// Client request header scheme to match on. Valid values: http, https.
	Scheme *string `json:"scheme,omitempty" tf:"scheme,omitempty"`
}

type SpecHttp2RouteMatchObservation struct {

	// Client request headers to match on.
	Header []HeaderObservation `json:"header,omitempty" tf:"header,omitempty"`

	// Client request header method to match on. Valid values: GET, HEAD, POST, PUT, DELETE, CONNECT, OPTIONS, TRACE, PATCH.
	Method *string `json:"method,omitempty" tf:"method,omitempty"`

	// The port number to match from the request.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// Value sent by the client must begin with the specified characters. Must be between 1 and 255 characters in length.
	Prefix *string `json:"prefix,omitempty" tf:"prefix,omitempty"`

	// Client request header scheme to match on. Valid values: http, https.
	Scheme *string `json:"scheme,omitempty" tf:"scheme,omitempty"`
}

type SpecHttp2RouteMatchParameters struct {

	// Client request headers to match on.
	Header []HeaderParameters `json:"header,omitempty" tf:"header,omitempty"`

	// Client request header method to match on. Valid values: GET, HEAD, POST, PUT, DELETE, CONNECT, OPTIONS, TRACE, PATCH.
	Method *string `json:"method,omitempty" tf:"method,omitempty"`

	// The port number to match from the request.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// Value sent by the client must begin with the specified characters. Must be between 1 and 255 characters in length.
	Prefix *string `json:"prefix,omitempty" tf:"prefix,omitempty"`

	// Client request header scheme to match on. Valid values: http, https.
	Scheme *string `json:"scheme,omitempty" tf:"scheme,omitempty"`
}

type SpecHttp2RouteObservation struct {

	// Action to take if a match is determined.
	Action []SpecHttp2RouteActionObservation `json:"action,omitempty" tf:"action,omitempty"`

	// Criteria for determining an gRPC request match.
	Match []SpecHttp2RouteMatchObservation `json:"match,omitempty" tf:"match,omitempty"`

	// Retry policy.
	RetryPolicy []Http2RouteRetryPolicyObservation `json:"retryPolicy,omitempty" tf:"retry_policy,omitempty"`

	// Types of timeouts.
	Timeout []Http2RouteTimeoutObservation `json:"timeout,omitempty" tf:"timeout,omitempty"`
}

type SpecHttp2RouteParameters struct {

	// Action to take if a match is determined.
	Action []SpecHttp2RouteActionParameters `json:"action,omitempty" tf:"action,omitempty"`

	// Criteria for determining an gRPC request match.
	Match []SpecHttp2RouteMatchParameters `json:"match,omitempty" tf:"match,omitempty"`

	// Retry policy.
	RetryPolicy []Http2RouteRetryPolicyParameters `json:"retryPolicy,omitempty" tf:"retry_policy,omitempty"`

	// Types of timeouts.
	Timeout []Http2RouteTimeoutParameters `json:"timeout,omitempty" tf:"timeout,omitempty"`
}

type TCPRouteActionInitParameters struct {

	// Targets that traffic is routed to when a request matches the route.
	// You can specify one or more targets and their relative weights with which to distribute traffic.
	WeightedTarget []TCPRouteActionWeightedTargetInitParameters `json:"weightedTarget,omitempty" tf:"weighted_target,omitempty"`
}

type TCPRouteActionObservation struct {

	// Targets that traffic is routed to when a request matches the route.
	// You can specify one or more targets and their relative weights with which to distribute traffic.
	WeightedTarget []TCPRouteActionWeightedTargetObservation `json:"weightedTarget,omitempty" tf:"weighted_target,omitempty"`
}

type TCPRouteActionParameters struct {

	// Targets that traffic is routed to when a request matches the route.
	// You can specify one or more targets and their relative weights with which to distribute traffic.
	WeightedTarget []TCPRouteActionWeightedTargetParameters `json:"weightedTarget,omitempty" tf:"weighted_target,omitempty"`
}

type TCPRouteActionWeightedTargetInitParameters struct {

	// The port number to match from the request.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// Virtual node to associate with the weighted target. Must be between 1 and 255 characters in length.
	// +crossplane:generate:reference:type=github.com/upbound/provider-aws/apis/appmesh/v1beta1.VirtualNode
	// +crossplane:generate:reference:extractor=github.com/upbound/upjet/pkg/resource.ExtractParamPath("name",false)
	VirtualNode *string `json:"virtualNode,omitempty" tf:"virtual_node,omitempty"`

	VirtualNodeRef *v1.Reference `json:"virtualNodeRef,omitempty" tf:"-"`

	VirtualNodeSelector *v1.Selector `json:"virtualNodeSelector,omitempty" tf:"-"`

	// Relative weight of the weighted target. An integer between 0 and 100.
	Weight *float64 `json:"weight,omitempty" tf:"weight,omitempty"`
}

type TCPRouteActionWeightedTargetObservation struct {

	// The port number to match from the request.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// Virtual node to associate with the weighted target. Must be between 1 and 255 characters in length.
	VirtualNode *string `json:"virtualNode,omitempty" tf:"virtual_node,omitempty"`

	// Relative weight of the weighted target. An integer between 0 and 100.
	Weight *float64 `json:"weight,omitempty" tf:"weight,omitempty"`
}

type TCPRouteActionWeightedTargetParameters struct {

	// The port number to match from the request.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// Virtual node to associate with the weighted target. Must be between 1 and 255 characters in length.
	// +crossplane:generate:reference:type=github.com/upbound/provider-aws/apis/appmesh/v1beta1.VirtualNode
	// +crossplane:generate:reference:extractor=github.com/upbound/upjet/pkg/resource.ExtractParamPath("name",false)
	VirtualNode *string `json:"virtualNode,omitempty" tf:"virtual_node,omitempty"`

	// Reference to a VirtualNode in appmesh to populate virtualNode.
	// +kubebuilder:validation:Optional
	VirtualNodeRef *v1.Reference `json:"virtualNodeRef,omitempty" tf:"-"`

	// Selector for a VirtualNode in appmesh to populate virtualNode.
	// +kubebuilder:validation:Optional
	VirtualNodeSelector *v1.Selector `json:"virtualNodeSelector,omitempty" tf:"-"`

	// Relative weight of the weighted target. An integer between 0 and 100.
	Weight *float64 `json:"weight,omitempty" tf:"weight,omitempty"`
}

type TCPRouteInitParameters struct {

	// Action to take if a match is determined.
	Action []TCPRouteActionInitParameters `json:"action,omitempty" tf:"action,omitempty"`

	// Criteria for determining an gRPC request match.
	Match []TCPRouteMatchInitParameters `json:"match,omitempty" tf:"match,omitempty"`

	// Types of timeouts.
	Timeout []TCPRouteTimeoutInitParameters `json:"timeout,omitempty" tf:"timeout,omitempty"`
}

type TCPRouteMatchInitParameters struct {

	// The port number to match from the request.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`
}

type TCPRouteMatchObservation struct {

	// The port number to match from the request.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`
}

type TCPRouteMatchParameters struct {

	// The port number to match from the request.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`
}

type TCPRouteObservation struct {

	// Action to take if a match is determined.
	Action []TCPRouteActionObservation `json:"action,omitempty" tf:"action,omitempty"`

	// Criteria for determining an gRPC request match.
	Match []TCPRouteMatchObservation `json:"match,omitempty" tf:"match,omitempty"`

	// Types of timeouts.
	Timeout []TCPRouteTimeoutObservation `json:"timeout,omitempty" tf:"timeout,omitempty"`
}

type TCPRouteParameters struct {

	// Action to take if a match is determined.
	Action []TCPRouteActionParameters `json:"action,omitempty" tf:"action,omitempty"`

	// Criteria for determining an gRPC request match.
	Match []TCPRouteMatchParameters `json:"match,omitempty" tf:"match,omitempty"`

	// Types of timeouts.
	Timeout []TCPRouteTimeoutParameters `json:"timeout,omitempty" tf:"timeout,omitempty"`
}

type TCPRouteTimeoutIdleInitParameters struct {

	// Unit of time. Valid values: ms, s.
	Unit *string `json:"unit,omitempty" tf:"unit,omitempty"`

	// Number of time units. Minimum value of 0.
	Value *float64 `json:"value,omitempty" tf:"value,omitempty"`
}

type TCPRouteTimeoutIdleObservation struct {

	// Unit of time. Valid values: ms, s.
	Unit *string `json:"unit,omitempty" tf:"unit,omitempty"`

	// Number of time units. Minimum value of 0.
	Value *float64 `json:"value,omitempty" tf:"value,omitempty"`
}

type TCPRouteTimeoutIdleParameters struct {

	// Unit of time. Valid values: ms, s.
	Unit *string `json:"unit,omitempty" tf:"unit,omitempty"`

	// Number of time units. Minimum value of 0.
	Value *float64 `json:"value,omitempty" tf:"value,omitempty"`
}

type TCPRouteTimeoutInitParameters struct {

	// Idle timeout. An idle timeout bounds the amount of time that a connection may be idle.
	Idle []TCPRouteTimeoutIdleInitParameters `json:"idle,omitempty" tf:"idle,omitempty"`
}

type TCPRouteTimeoutObservation struct {

	// Idle timeout. An idle timeout bounds the amount of time that a connection may be idle.
	Idle []TCPRouteTimeoutIdleObservation `json:"idle,omitempty" tf:"idle,omitempty"`
}

type TCPRouteTimeoutParameters struct {

	// Idle timeout. An idle timeout bounds the amount of time that a connection may be idle.
	Idle []TCPRouteTimeoutIdleParameters `json:"idle,omitempty" tf:"idle,omitempty"`
}

type TimeoutIdleInitParameters struct {

	// Unit of time. Valid values: ms, s.
	Unit *string `json:"unit,omitempty" tf:"unit,omitempty"`

	// Number of time units. Minimum value of 0.
	Value *float64 `json:"value,omitempty" tf:"value,omitempty"`
}

type TimeoutIdleObservation struct {

	// Unit of time. Valid values: ms, s.
	Unit *string `json:"unit,omitempty" tf:"unit,omitempty"`

	// Number of time units. Minimum value of 0.
	Value *float64 `json:"value,omitempty" tf:"value,omitempty"`
}

type TimeoutIdleParameters struct {

	// Unit of time. Valid values: ms, s.
	Unit *string `json:"unit,omitempty" tf:"unit,omitempty"`

	// Number of time units. Minimum value of 0.
	Value *float64 `json:"value,omitempty" tf:"value,omitempty"`
}

type TimeoutInitParameters struct {

	// Idle timeout. An idle timeout bounds the amount of time that a connection may be idle.
	Idle []IdleInitParameters `json:"idle,omitempty" tf:"idle,omitempty"`

	// Per request timeout.
	PerRequest []PerRequestInitParameters `json:"perRequest,omitempty" tf:"per_request,omitempty"`
}

type TimeoutObservation struct {

	// Idle timeout. An idle timeout bounds the amount of time that a connection may be idle.
	Idle []IdleObservation `json:"idle,omitempty" tf:"idle,omitempty"`

	// Per request timeout.
	PerRequest []PerRequestObservation `json:"perRequest,omitempty" tf:"per_request,omitempty"`
}

type TimeoutParameters struct {

	// Idle timeout. An idle timeout bounds the amount of time that a connection may be idle.
	Idle []IdleParameters `json:"idle,omitempty" tf:"idle,omitempty"`

	// Per request timeout.
	PerRequest []PerRequestParameters `json:"perRequest,omitempty" tf:"per_request,omitempty"`
}

type TimeoutPerRequestInitParameters struct {

	// Unit of time. Valid values: ms, s.
	Unit *string `json:"unit,omitempty" tf:"unit,omitempty"`

	// Number of time units. Minimum value of 0.
	Value *float64 `json:"value,omitempty" tf:"value,omitempty"`
}

type TimeoutPerRequestObservation struct {

	// Unit of time. Valid values: ms, s.
	Unit *string `json:"unit,omitempty" tf:"unit,omitempty"`

	// Number of time units. Minimum value of 0.
	Value *float64 `json:"value,omitempty" tf:"value,omitempty"`
}

type TimeoutPerRequestParameters struct {

	// Unit of time. Valid values: ms, s.
	Unit *string `json:"unit,omitempty" tf:"unit,omitempty"`

	// Number of time units. Minimum value of 0.
	Value *float64 `json:"value,omitempty" tf:"value,omitempty"`
}

type WeightedTargetInitParameters struct {

	// The port number to match from the request.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// Virtual node to associate with the weighted target. Must be between 1 and 255 characters in length.
	VirtualNode *string `json:"virtualNode,omitempty" tf:"virtual_node,omitempty"`

	// Relative weight of the weighted target. An integer between 0 and 100.
	Weight *float64 `json:"weight,omitempty" tf:"weight,omitempty"`
}

type WeightedTargetObservation struct {

	// The port number to match from the request.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// Virtual node to associate with the weighted target. Must be between 1 and 255 characters in length.
	VirtualNode *string `json:"virtualNode,omitempty" tf:"virtual_node,omitempty"`

	// Relative weight of the weighted target. An integer between 0 and 100.
	Weight *float64 `json:"weight,omitempty" tf:"weight,omitempty"`
}

type WeightedTargetParameters struct {

	// The port number to match from the request.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// Virtual node to associate with the weighted target. Must be between 1 and 255 characters in length.
	VirtualNode *string `json:"virtualNode,omitempty" tf:"virtual_node,omitempty"`

	// Relative weight of the weighted target. An integer between 0 and 100.
	Weight *float64 `json:"weight,omitempty" tf:"weight,omitempty"`
}

// RouteSpec defines the desired state of Route
type RouteSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     RouteParameters `json:"forProvider"`
	// THIS IS AN ALPHA FIELD. Do not use it in production. It is not honored
	// unless the relevant Crossplane feature flag is enabled, and may be
	// changed or removed without notice.
	InitProvider RouteInitParameters `json:"initProvider,omitempty"`
}

// RouteStatus defines the observed state of Route.
type RouteStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        RouteObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// Route is the Schema for the Routes API. Provides an AWS App Mesh route resource.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,aws}
type Route struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || has(self.initProvider.name)",message="%!s(MISSING) is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.spec) || has(self.initProvider.spec)",message="%!s(MISSING) is a required parameter"
	Spec   RouteSpec   `json:"spec"`
	Status RouteStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RouteList contains a list of Routes
type RouteList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Route `json:"items"`
}

// Repository type metadata.
var (
	Route_Kind             = "Route"
	Route_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Route_Kind}.String()
	Route_KindAPIVersion   = Route_Kind + "." + CRDGroupVersion.String()
	Route_GroupVersionKind = CRDGroupVersion.WithKind(Route_Kind)
)

func init() {
	SchemeBuilder.Register(&Route{}, &RouteList{})
}
